"""add now_playing and play_history tables

Revision ID: 5bb46508476b
Revises: 003
Create Date: 2026-02-04 21:45:31.499520

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5bb46508476b"
down_revision = "003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "now_playing",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("artist", sa.String(length=255), nullable=False),
        sa.Column("album", sa.String(length=255), nullable=True),
        sa.Column("deck", sa.String(length=10), nullable=True),
        sa.Column("spotify_track_id", sa.String(length=100), nullable=True),
        sa.Column("album_art_url", sa.String(length=500), nullable=True),
        sa.Column("spotify_uri", sa.String(length=100), nullable=True),
        sa.Column("matched_request_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("bridge_connected", sa.Boolean(), nullable=False),
        sa.Column("bridge_device_name", sa.String(length=100), nullable=True),
        sa.Column("bridge_last_seen", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["matched_request_id"], ["requests.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_now_playing_event_id"), "now_playing", ["event_id"], unique=True)
    op.create_table(
        "play_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("artist", sa.String(length=255), nullable=False),
        sa.Column("album", sa.String(length=255), nullable=True),
        sa.Column("deck", sa.String(length=10), nullable=True),
        sa.Column("spotify_track_id", sa.String(length=100), nullable=True),
        sa.Column("album_art_url", sa.String(length=500), nullable=True),
        sa.Column("spotify_uri", sa.String(length=100), nullable=True),
        sa.Column("matched_request_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("play_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["matched_request_id"], ["requests.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_play_history_event_id"), "play_history", ["event_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_play_history_event_id"), table_name="play_history")
    op.drop_table("play_history")
    op.drop_index(op.f("ix_now_playing_event_id"), table_name="now_playing")
    op.drop_table("now_playing")
    # ### end Alembic commands ###
